version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: apt-get install -y sudo
      - run: echo hallo
      - run: ls -al /bin/sh && sudo rm /bin/sh && sudo on -s /bin/bash /bin/sh && ls -al /bin/sh
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
