version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test
